name: Verificador de links quebrados

on:
  schedule:
    - cron: 0 8 * * * # Run daily at 8am
  workflow_dispatch:

permissions:
  issues: write
  
jobs:
  check:
    name: Broken links checker
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      # https://github.com/stevenvachon/broken-link-checker
      - name: Install broken link checker
        run: npm install broken-link-checker -g

      - name: Check for broken links
        run: blc https://historiaonline.com -r
