name: Site Checks

on:
  schedule:
    - cron: '* * * * *' # Every 5 minuts
  workflow_dispatch:

env:
  SITE_URL: https://historiaonline.com
  
jobs:
  check:
    name: Site checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Home page curl succeeds
        run: curl -fs -w "%{http_code}" ${SITE_URL}
        
      - name: Home page does not have links for domain containing www
        run: exit $(curl -s ${SITE_URL} 2>&1 |grep -cF https://historiaonline.com)
