name: Site Checks

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutse
  workflow_dispatch:

env:
  SITE_URL: https://historiaonline.com
  
jobs:
  check:
    name: Site checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Home page curl succeeds
        run: curl -fs -w "%{http_code}" ${SITE_URL}
 
      - name: Home does not have links for wwww domain
        run: exit $(curl -s ${SITE_URL} 2>&1 |grep -cF https://www.historiaonline.com)
        
      - name: Home does not have links for wordpress domain
        run: exit $(curl -s ${SITE_URL} 2>&1 |grep -cF http://wordpress.historiaonline.com)        
